name: Release

on:
  release:
    types: [published]

jobs:
  release-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload purifier-card.js to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PAT_TOKEN }}
          file: purifier-card.js
          asset_name: purifier-card.js
          tag: ${{ github.event.release.tag_name }}
          overwrite: true
